name: Base64 Decoder

on:
  schedule:
    - cron: '0 0 * * *'  # 每天 UTC 时间 0 点自动运行
  workflow_dispatch:      # 添加手动触发选项

jobs:
  decode:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 需要设置 fetch-depth: 0 才能正常推送
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests

    - name: Run decoding script
      run: |
        python -c "import requests
        import base64

        url = 'https://lucky-term-fea6.tel13339999091.workers.dev/'

        try:
            response = requests.get(url)
            response.raise_for_status()
            encoded_content = response.text.strip()
            
            decoded_bytes = base64.b64decode(encoded_content)
            
            # 将原始字节写入文件
            with open('hy2.txt', 'wb') as f:
                f.write(decoded_bytes)
            
            print('::notice::内容已保存到 hy2.txt')
            
            try:
                # 仅用于日志输出验证
                decoded_content = decoded_bytes.decode('utf-8')
                print('解码后的内容：\\n', decoded_content)
            except UnicodeDecodeError:
                print('::warning::内容非UTF-8格式，已保存原始字节')
            
        except requests.exceptions.RequestException as e:
            print(f'::error::请求出错：{e}')
            exit(1)
        except base64.binascii.Error as e:
            print(f'::error::Base64解码失败：{e}')
            exit(1)
        "

    - name: Commit file
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git add hy2.txt
        # 仅当文件有变更时提交
        if git diff-index --quiet HEAD --; then
          echo "没有检测到文件变更"
        else
          git commit -m "自动更新 hy2 文件 [skip ci]"
          git push
        fi
